export const DEVELOPMENT_SERVER = 'http://localhost:5000/api/v1';
export const DARKDOCS_SHOP_USER_KEY = 'DARKDOCS_SHOP_USER_KEY';
export const DARKDOCS_SHOP_TOKEN_KEY = 'DARKDOCS_SHOP_TOKEN_KEY';
export const DARKDOCS_SHOP_ORDERS_KEY = 'DARKDOCS_SHOP_ORDERS_KEY';
